behaviors:
  BehaviorAgentAlpiniste:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    checkpoint_interval: 500000
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.86
        strength: 1.0
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 15000000
    time_horizon: 64
    summary_freq: 5000
